=== markussundstrom/synthboss/data/synthboss-synth-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "synth-definition",
    "title": "Synthboss synth configuration schema",
    "description": "Declaration of a synth's parameters",
    "type": "object",
    "properties": {
        "manufacturer": {
            "type": "string"
        },
        "model": {
            "type": "string"
        },
        "shortname": {
            "type": "string",
            "pattern": "^[a-z0-9]{3,}$"
        },
        "parts": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "channel": {
                        "type": "integer"
                    },
                    "messageformat": {
                        "type": "array",
                        "items": {
                            "oneOf": [
                                {
                                    "type": "integer"
                                },
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "op": {
                                            "type": "string"
                                        },
                                        "arg1": {
                                            "oneOf": [
                                                {
                                                    "type": "integer"
                                                },
                                                {
                                                    "type": "string"
                                                }
                                            ]
                                        },
                                        "arg2": {
                                            "oneOf": [
                                                {
                                                    "type": "integer"
                                                },
                                                {
                                                    "type": "string"
                                                }
                                            ]
                                        }
                                    },
                                    "required": ["op", "arg1", "arg2"]
                                }
                            ]
                        }
                    },
                    "sections": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string"
                                },
                                "parameters": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "name": {
                                                "type": "string"
                                            },
                                            "parameternumber": {
                                                "type": "integer"
                                            },
                                            "class": {
                                                "type": "string"
                                            },
                                            "coherence": {
                                                "type": "integer"
                                            },
                                            "value": {
                                                "type": "integer"
                                            },
                                            "encoding": {
                                                "type": "object",
                                                "properties": {
                                                    "type": {
                                                        "type": "string"
                                                    },
                                                    "valuebits": {
                                                        "type": "integer"
                                                    },
                                                    "signbit": {
                                                        "type": "integer"
                                                    },
                                                    "offset": {
                                                        "type": "integer"
                                                    }
                                                },
                                                "dependencies" : {
                                                    "type": {
                                                        "oneOf": [
                                                            {
                                                                "properties": {"type": {"enum": ["unsigned"]}},
                                                                "required": ["valuebits"]
                                                            },
                                                            {
                                                                "properties": {"type": {"enum": ["signed"]}},
                                                                "required": ["valuebits", "signbit"]
                                                            }
                                                        ]
                                                    }
                                                }
                                            },
                                            "min": {
                                                "type": "integer"
                                            },
                                            "max": {
                                                "type": "integer"
                                            },
                                            "on": {
                                                "type": "integer"
                                            },
                                            "off": {
                                                "type": "integer"
                                            },
                                            "choices": {
                                                "type": "array",
                                                "items": {
                                                    "type": "object",
                                                    "properties": {
                                                        "name": {
                                                            "type": "string"
                                                        },
                                                        "optionvalue": {
                                                            "type": "integer"
                                                        }
                                                    }
                                                }
                                            }
                                        },
                                        "dependencies": {
                                            "class": {
                                                "oneOf": [
                                                    {
                                                        "properties": {"class": {"enum": ["range"]}},
                                                        "required": ["min", "max"]
                                                    },
                                                    {
                                                        "properties": {"class": {"enum": ["toggle"]}},
                                                        "required": ["on", "off"]
                                                    },
                                                    {
                                                        "properties": {"class": {"enum": ["select"]}},
                                                        "required": ["choices"]
                                                    }
                                                ]
                                            }
                                        },
                                        "required": [ "name", "parameternumber", "class", "value" ]
                                    }
                                }
                            },
                            "required": [ "parameters" ]
                        }
                    }
                },
                "required": [ "messageformat", "channel", "sections" ]
            }
        }
    },
    "required": [ "manufacturer", "model", "shortname" ]
}

=== markussundstrom/synthboss/data/devices/k3m.json
{
    "manufacturer": "Kawai",
    "model": "K3",
    "shortname": "k3m",
    "parts": [
        {
            "name": "K3m",
            "channel": 1,
            "messageformat": [
                240, 64, {"op": "sub", "arg1": "channel", "arg2": 1}, 
                16, 0, 1, "parameter", {"op": "rshift", "arg1": "value", "arg2": 4},
                {"op": "and", "arg1": "value", "arg2": 15}, 247
            ],
            "sections": [
                {
                    "name": "OSC",
                    "parameters": [
                        {
                            "name": "MONO",
                            "parameternumber": 5,
                            "class": "toggle",
                            "coherence": 5,
                            "on": 128,
                            "off": 0,
                            "value": 0
                        },
                        {
                            "name": "OSC 1 WAVE",
                            "parameternumber": 1,
                            "class": "select",
                            "choices": [
                                {
                                    "name": "NONE",
                                    "optionvalue": 0
                                },
                                {
                                    "name": "01 Grand Piano I",
                                    "optionvalue": 1
                                },
                                {
                                    "name": "02 Bell",
                                    "optionvalue": 2
                                },
                                {
                                    "name": "03 Strings",
                                    "optionvalue": 3
                                },
                                {
                                    "name": "04 E. Bass",
                                    "optionvalue": 4
                                },
                                {
                                    "name": "05 Oboe",
                                    "optionvalue": 5
                                },
                                {
                                    "name": "06 E. Piano I",
                                    "optionvalue": 6
                                },
                                {
                                    "name": "07 Organ",
                                    "optionvalue": 7
                                },
                                {
                                    "name": "08 Brass 1",
                                    "optionvalue": 8
                                },
                                {
                                    "name": "09 Digital Bell",
                                    "optionvalue": 9
                                },
                                {
                                    "name": "10 Slap Bass",
                                    "optionvalue": 10
                                },
                                {
                                    "name": "11 Plucked String",
                                    "optionvalue": 11
                                },
                                {
                                    "name": "12 Classic Guitar",
                                    "optionvalue": 12
                                },
                                {
                                    "name": "13 Hammered Tine",
                                    "optionvalue": 13
                                },
                                {
                                    "name": "14 Metallic Wave",
                                    "optionvalue": 14
                                },
                                {
                                    "name": "15 Vox Humana",
                                    "optionvalue": 15
                                },
                                {
                                    "name": "16 Sharp Wave",
                                    "optionvalue": 16
                                },
                                {
                                    "name": "17 Digital Harmonics",
                                    "optionvalue": 17
                                },
                                {
                                    "name": "18 Pipe Organ",
                                    "optionvalue": 18
                                },
                                {
                                    "name": "19 Wood Bass",
                                    "optionvalue": 19
                                },
                                {
                                    "name": "20 Resonant Strings",
                                    "optionvalue": 20
                                },
                                {
                                    "name": "21 E. Piano II",
                                    "optionvalue": 21
                                },
                                {
                                    "name": "22 Jazz Organ",
                                    "optionvalue": 22
                                },
                                {
                                    "name": "23 Glocken",
                                    "optionvalue": 23
                                },
                                {
                                    "name": "24 Oriental Bell",
                                    "optionvalue": 24
                                },
                                {
                                    "name": "25 Harpsichord",
                                    "optionvalue": 25
                                },
                                {
                                    "name": "26 Trumpet",
                                    "optionvalue": 26
                                },
                                {
                                    "name": "27 Sax",
                                    "optionvalue": 27
                                },
                                {
                                    "name": "28 Grand Piano II",
                                    "optionvalue": 28
                                },
                                {
                                    "name": "29 Square",
                                    "optionvalue": 29
                                },
                                {
                                    "name": "30 Sawtooth",
                                    "optionvalue": 30
                                },
                                {
                                    "name": "31 Sine",
                                    "optionvalue": 31
                                },
                                {
                                    "name": "32 Programmable Wave",
                                    "optionvalue": 32
                                },
                                {
                                    "name": "33 White Noise",
                                    "optionvalue": 33
                                }
                            ],
                            "value": 1
                        },
                        {
                            "name": "RANGE",
                            "parameternumber": 1,
                            "class": "select",
                            "choices": [
                                {
                                    "name": "16'",
                                    "optionvalue": 0
                                },
                                {
                                    "name": "8'",
                                    "optionvalue": 64
                                },
                                {
                                    "name": "4'",
                                    "optionvalue": 128
                                }
                            ],
                            "value": 64
                        },
                        {
                            "name": "PORTA",
                            "parameternumber": 3,
                            "class": "toggle",
                            "coherence": 3,
                            "on": 128,
                            "off": 0,
                            "value": 0
                        },
                        {
                            "name": "PORTA SPEED",
                            "parameternumber": 3,
                            "class": "range",
                            "coherence": 3,
                            "min": 0,
                            "max": 99,
                            "value": 0
                        },
                        {
                            "name": "BALANCE",
                            "parameternumber": 4,
                            "class": "range",
                            "min": -15,
                            "max": 15,
                            "encoding": {
                                "type": "signed",
                                "valuebits": 4,
                                "signbit": 7
                            },
                            "value": 0
                        },
                        {
                            "name": "PITCH BEND",
                            "parameternumber": 5,
                            "class": "range",
                            "coherence": 5,
                            "min": 1,
                            "max": 7,
                            "value": 2
                        },
                        {
                            "name": "AUTOBEND",
                            "parameternumber": 6,
